services:
  - type: web
    name: aden-api
    env: node
    plan: free
    region: oregon
    branch: master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true